### ISSUE TITLE
Inconsistent layout behavior?

### ISSUE THREAD

**Issue by tscode** [jkrumbiegel/GridLayoutBase.jl#62]
I am not sure if this is intended behavior if one understands the internals better than I do, but I am confused by the following:

I want to create a red box that frames some content to be dynamically defined by a function (`plot_something_great`). This example works just as intended:
```julia
using GLMakie

function plot_something_great(layout)
  sublayout = GridLayout(layout[1, 1], 1, 1)
  Box(sublayout[:, :], color = :blue, height = 50)
end

fig = Figure()
layout = GridLayout(fig[1, 1])
Box(layout[:,:], color = :red, alignmode = Outside(-15))
plot_something_great(layout)
```
![image](https://github.com/user-attachments/assets/e4f6fdae-6047-4246-a6fe-4b88369e6bb2)

However, if `sublayout` has a row number different from 1, `layout` does not respect the fixed height of `sublayout` anymore.
```julia
function plot_something_great(layout)
  sublayout = GridLayout(layout[1, 1], 2, 1)
  Box(sublayout[:, :], color = :blue, height = 50)
end
```
![image](https://github.com/user-attachments/assets/5bebd40c-ff53-4c82-8c47-7bd36eab6df7)

Can I somehow get the former behavior if `sublayout` is more complex? (In practice I won't know the height `50`, only that the content placed by `plot_something_great` has some runtime dependent height)

**Comment by jkrumbiegel** [comment]
Yes this is expected because a GridLayout checks each row and column separately for fixed size content placed there. Multicolumn or multirow content is ignored for that purpose because it would not be clear how to distribute column sizes if there are multiple objects overlapping partially the same set of columns for example. So only the simple version with a single column or row is supported.

In your case you test auto sizing with a Box spanning two rows. But you don't need the two rows in the example so maybe your actual use case can be restructured a little so it works. One can usually solve the problem with a nested GridLayout within a single row/column where before one was using a multirow / multicolumn object.

Maybe show what you actually wanted to place in your plotting function so I can give better suggestions :)

**Comment by tscode** [comment]
I see, thanks! While I was trying to construct a more realistic minimal use-case, I was stumbling upon a solution :) And of course, it was obvious...

For the historical record: I want to be able to place several "Widgets" in a figure, where each widget could have (runtime-dependent) layout requirements. Sometimes the height / width of the widget is adaptive, then the current behavior is perfectly fine. Sometimes, however, the widget might  enforce a fixed height (e.g., the widget is just a table of labels).

This was the approach I had problems with, where the frame is controlled outside of the widget logic:
```julia
using GLMakie
using Makie.GridLayoutBase: Outer

struct MyWidget end

function plotframe(layout)
  Box(
    layout[:, :, Outer()],
    color = :white,
    strokecolor = :gray,
    cornerradius = 10,
  )
end

function plotwidget(layout, ::MyWidget)
  sublayout = GridLayout(
    layout[1, 1],
    3,
    2,
    alignmode = Outside(15),
  )
  rowsize!(sublayout, 2, Aspect(1, 1.0))

  Label(
    sublayout[1, :],
    "Widget Title",
    font = :bold,
    halign = :left
  )
  Button(sublayout[1, :], label="Export", halign = :right)
  Axis(sublayout[2, 1])
  Axis(sublayout[2, 2])
  Slider(sublayout[3, :])
  return
end

# This part of the code does not know what layout user-defined widgets might require
fig = Figure(backgroundcolor = :lightgray)
widget_frame_layout = GridLayout(fig[1, 1])
plotframe(widget_frame_layout)

# Here, different widgets will need different sub-layouts
plotwidget(widget_frame_layout, MyWidget())
fig
```
![image](https://github.com/user-attachments/assets/00fc1a30-2221-49c8-ab21-b237a619babd)

However, if I let the widget draw the frame itself (which is fine, might just require passing some more theming arguments), then it works the way I want it:
```julia

function plotframe2(layout)
  Box(
    layout[:, :, Outer()],
    color = :white,
    strokecolor = :gray,
    cornerradius = 10,
    alignmode = Outside(-15)
  )
end

function plotwidget2(layout, ::MyWidget)
  sublayout = GridLayout(
    layout[1, 1],
    3,
    2,
    alignmode = Outside(15),
  )
  plotframe2(sublayout)  # Here we plot the frame
  rowsize!(sublayout, 2, Aspect(1, 1.0))

  Label(
    sublayout[1, :],
    "Widget Title",
    font = :bold,
    halign = :left
  )
  Button(sublayout[1, :], label="Export", halign = :right)
  Axis(sublayout[2, 1])
  Axis(sublayout[2, 2])
  Slider(sublayout[3, :])
  return
end

fig2 = Figure(backgroundcolor = :lightgray)
widget_parent_layout = GridLayout(fig2[1, 1])
plotwidget2(widget_parent_layout, MyWidget())
fig2
```
![image](https://github.com/user-attachments/assets/7c6dc0ad-0205-485f-9b53-9f06c089e84b)
